accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crackers.urls')),
    path('accounts/', include('accounts.urls')),
]

crackers/urls.py
from django.urls import path

from . import views

app_name = 'tracks'
urlpatterns = [
    path('', views.index, name='index'),   # all objectives. 이후 로그인 되어있지 않으면 landingpage, 되어있다면 all objectives.
    path('create/', views.create, name='create'),   # create task
    path('<int:supertask_pk>/', views.tasks, name='tasks'),   # subtask list
    path('<int:supertask_pk>/create/', views.create, name='create_subtask'),   # create subtask
    path('<int:supertask_pk>/detail/', views.detail, name='detail'),
    path('<int:task_pk>/update/', views.update, name='update'),
    path('<int:task_pk>/delete/', views.delete, name='delete'),
    path('<int:task_pk>/complete/', views.complete, name='complete'),
    path('<int:supertask_pk>/detail_paginator/', views.detail_paginator, name='detail_paginator'),
    path('<int:task_pk>/move/', views.move_objective, name='move_objective'),
    path('<int:task_pk>/move/<int:target_pk>/', views.move_task, name='move_task'),
    path('delete-selected/', views.delete_selected, name='delete_selected')
]

crackers/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import F, FloatField, Sum, Case, When, Max, Subquery, OuterRef
from django.db.models.functions import Coalesce

from .signals import achievement_reassessment_signal


class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField('title', max_length=100)
    description = models.TextField('description', null=True, blank=True)
    supertask = models.ForeignKey('self', verbose_name='supertask', on_delete=models.CASCADE, blank=True, null=True, related_name='subtasks')
    completed = models.BooleanField('completed', default=False)
    # marked_complete = models.BooleanField('marked complete', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    proportion = models.IntegerField('proportion', validators=[MinValueValidator(0)])   # 이 Task가 Supertask 또는 Objective에서 차지하는 비중
    achievement = models.FloatField('achievement', default=0, validators=[MaxValueValidator(1.0), MinValueValidator(0.0)])
    accumulative = models.BooleanField('accumulative', default=False)   # 서브태스크 생성시 proportion을 누적합으로 입력할 수 있게
    
    # if accumulative, where to start?
    start = models.IntegerField(default=0)
    
    # type = models.CharField('type', max_length=50, null=True, blank=True, default=None)
    # duration = models.DurationField('duration', null=True, blank=True)
    # total = models.IntegerField('total', default=10_000)

    @property
    def pseudo_achievement(self):
        if self.completed:
            return 1.0
        return self.achievement

    @property
    def marked_complete(self):
        return self.completed and self.subtasks.filter(completed=False, achievement__lt=1.0).exists()

    def assess_achievement(self):
        if self.subtasks.exists():
            subtasks = self.subtasks
            # subtasks = self.subtasks.order_by('proportion')
            if self.accumulative:
                subquery = Subquery(
                    self.subtasks.filter(proportion__lte=OuterRef('proportion')).exclude(pk=OuterRef('pk')).annotate(
                        greatest_among_the_lesser=Max('proportion', output_field=FloatField())
                    ).values('greatest_among_the_lesser')[:1]
                )
                subtasks = subtasks.annotate(greatest_among_the_lesser=subquery).annotate(
                    adjusted_weight=F('proportion')-Coalesce('greatest_among_the_lesser', self.start, output_field=FloatField())
                )
                reference = F('adjusted_weight')
                proportion_total = Max('proportion', output_field=FloatField()) - self.start
            else:
                reference = F('proportion')
                proportion_total = Sum('proportion', output_field=FloatField())
            weighted_achievement_total = subtasks.annotate(
                weighted_achievement=Case(   # pseudo_achievement
                    When(completed=True, then=reference),
                    default=F('achievement')*reference,
                    output_field=FloatField(),
                )
            ).values('weighted_achievement').aggregate(
                weighted_achievement_total=Sum('weighted_achievement', output_field=FloatField())
            ).get('weighted_achievement_total', 0)
            total = subtasks.aggregate(
                total=proportion_total
            ).get('total', 1)
            return weighted_achievement_total / total
        if self.completed:
            return 1.0
        return 0.0

    def breadcrumb(self):
        crumb = [self]
        supertask = self.supertask
        while supertask is not None:
            crumb.append(supertask)
            supertask = supertask.supertask
        # return reversed(crumb)   # iterator, not list
        crumb.reverse()
        return crumb

    def save(self, *args, **kwargs):
        supertask = self.supertask
        super().save(*args, **kwargs)
        achievement_reassessment_signal.send(sender=self.__class__, supertask=supertask)

    def delete(self, *args, **kwargs):
        supertask = self.supertask
        result = super().delete(*args, **kwargs)
        achievement_reassessment_signal.send(sender=self.__class__, supertask=supertask)
        return result

    class Meta:
        db_table = 'task'

crackers/forms.py
from django import forms

from .models import Task

class TaskForm(forms.ModelForm):
    proportion = forms.IntegerField(required=True, label='Weight')
    description = forms.CharField(required=False, label='Description')
    title = forms.CharField(required=True, label='Task Title')
    accumulative = forms.BooleanField(required=False, label=' 👈 Check to have your subtasks\' weight accumulated', widget=forms.CheckboxInput(attrs={'class': 'checkbox'}))

    class Meta:
        model = Task
        fields = (
            'title',
            'description',
            'proportion',
            'start',
            'accumulative',
        )

crackers/views.py
from django.http import QueryDict
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_GET
from django.core.paginator import Paginator  
from django.db.models import Q

from .forms import TaskForm
from .models import Task
from .utils import render, HttpResponse, HTTPResponseHXRedirect


@require_GET
def index(request):
    if request.user.is_authenticated:
        tasks = Task.objects.filter(supertask=None, user=request.user)
        context = {
            'tasks': tasks,
            'base_template': 'crackers/base/_objective.html',
        }
        return render(request, 'crackers/tasks.html', context)
    return render(request, 'crackers/landingpage.html')


@require_GET
@login_required
def tasks(request, supertask_pk):
    tasks = Task.objects.filter(supertask=supertask_pk, user=request.user)   # pk만 넘겨도 된다.
    supertask = get_object_or_404(Task, pk=supertask_pk, user=request.user)
    context = {
        'tasks': tasks,
        'supertask': supertask,
        'breadcrumb': supertask.breadcrumb(),
        'base_template': 'crackers/base/_task.html',
    }
    return render(request, 'crackers/tasks.html', context)


@require_http_methods(['GET', 'POST'])
@login_required
def create(request, supertask_pk=None):
    if request.method == 'POST':
        data = request.POST
        path = data.get('_path')
        form = TaskForm(data=data)
        if form.is_valid():
            task = form.save(commit=False)
            if supertask_pk is not None:
                task.supertask = get_object_or_404(Task, pk=supertask_pk)
            task.user = request.user
            task.save()
            return redirect(path)
    else:
        form = TaskForm()
        path = request.META.get('HTTP_REFERER')
    context = {
        'form': form,
        'title': 'Create Objective' if supertask_pk is None else 'Create Task',
        'path': path,
    }
    if supertask_pk:
        context['supertask'] = get_object_or_404(Task, pk=supertask_pk)
        context['action'] = reverse_lazy('tracks:create_subtask', kwargs={'supertask_pk': supertask_pk})
    else:
        context['action'] = reverse_lazy('tracks:create')
    return render(request, 'crackers/create.html', context)


@require_GET
def detail(request, supertask_pk):
    if request.user.is_authenticated:
        supertask = get_object_or_404(Task, pk=supertask_pk, user=request.user)
        paginator = Paginator(supertask.subtasks.order_by('pk'), 5)
        page = request.GET.get('page', '1')
        page_obj = paginator.get_page(page)
        context = {
            'supertask': supertask,
            'page_obj': page_obj,
            'subtasks': supertask.subtasks.filter(supertask=supertask_pk),
        }
        trigger = {
            'change-detail-btn': {
                'btnId': f'detail-btn-for-{supertask.pk}',
                'outerHTML': loader.render_to_string('crackers/components/detail_btn.html', {'supertask': supertask}, request)
            }
        }
        return render(request, 'crackers/components/detail.html', context, trigger=trigger)
    return HTTPResponseHXRedirect(redirect_to=reverse_lazy('accounts:login'))


@require_http_methods(['DELETE'])
@login_required
def delete(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk, user=request.user)
    supertask = task.supertask
    task.delete()
    if supertask is not None:
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('tracks:tasks', kwargs={'supertask_pk': supertask.pk}))
    return HTTPResponseHXRedirect(redirect_to=reverse_lazy('tracks:index'))


@require_http_methods(['GET', 'PUT'])
@login_required
def update(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk, user=request.user)
    if request.method == 'PUT':
        data = QueryDict(request.body).dict()
        path = data.pop('_path')
        form = TaskForm(data=data, instance=task)
        if form.is_valid():
            form.save()
            return HTTPResponseHXRedirect(redirect_to=path)
    else:
        form = TaskForm(instance=task)
        path = request.META.get('HTTP_REFERER')
    context = {
        'form': form,
        'path': path,
    }
    return render(request, 'crackers/update.html', context)


@require_http_methods(['PUT'])
@login_required
def complete(request, task_pk):
    task = get_object_or_404(Task, pk=task_pk, user=request.user)
    if task.completed:
        if task.subtasks.exists() and not task.subtasks.filter(completed=False).exists():
            return HTTPResponseHXRedirect(redirect_to=request.META.get('HTTP_REFERER'))
        task.completed = False
    else:
        task.completed = True
    task.achievement = task.assess_achievement()
    task.save()
    if task.marked_complete:
        trigger = {
            'task-marked-complete': {
                'identifier': f'task-progress-{task.pk}',
            },
        }
    else:
        trigger = {
            'change-achievement-width': {
                'identifier': f'task-progress-{task.pk}',
                'width': round(task.pseudo_achievement*100),
            },
        }
    if (supertask := task.supertask) is not None:
        if supertask.marked_complete:
            trigger['supertask-marked-complete'] = {
                'identifier': f'task-progress-{supertask.pk}',
            }
        else:
            trigger['change-supertask-achievement-width'] = {
                'identifier': f'task-progress-{supertask.pk}',
                'width': round(supertask.pseudo_achievement*100),
            }
    return HttpResponse(trigger=trigger)


@login_required
def detail_paginator(request, supertask_pk):
    page = request.GET.get('page', '1')
    supertask = get_object_or_404(Task, pk=supertask_pk, user=request.user)
    paginator = Paginator(supertask.subtasks.order_by('pk'), 5)
    page_obj = paginator.get_page(page)
    context = {
        'page_obj': page_obj,
        'supertask': supertask,
    }
    trigger = {
        'update-paginator': {
            'paginatorId': f'paginator-{supertask.pk}',
            'innerHTML': loader.render_to_string('crackers/components/paginator.html', context, request)
        }
    }
    return render(request, 'crackers/components/subtasks.html', context, trigger=trigger)


@require_http_methods(['GET', 'PUT'])
@login_required
def move_objective(request, task_pk):
    user = request.user
    task_query = Q(pk=task_pk, user=user)
    if request.method == 'PUT':
        current_task = get_object_or_404(Task, task_query)
        current_supertask = current_task.supertask
        current_task.supertask = None
        current_task.save()
        if current_supertask:
            current_supertask.achievement = current_supertask.assess_achievement()
            current_supertask.save()
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('tracks:index'))
    else:
        query = Q(supertask=None) & Q(user=user) & ~Q(pk=task_pk)
        tasks = Task.objects.filter(query).order_by('-pk')
        current_task = get_object_or_404(Task, task_query)
    context = {
        'tasks': tasks,
        'current_task': current_task,
        'target_pk': None,
    }
    return render(request, 'crackers/move.html', context)


@require_http_methods(['GET', 'PUT'])
@login_required
def move_task(request, task_pk, target_pk):
    user = request.user
    task_query = Q(pk=task_pk, user=user)
    target_query = Q(pk=target_pk, user=user)
    if request.method == 'PUT':
        current_task = get_object_or_404(Task, task_query)
        target = get_object_or_404(Task, target_query)
        current_supertask = current_task.supertask
        temp = target
        while temp is not None:
            if temp == current_task:
                return HttpResponse({'message': 'invalid request'})
            temp = temp.supertask
        current_task.supertask = target
        current_task.save()
        if current_supertask is not None:
            current_supertask.achievement = current_supertask.assess_achievement()
            current_supertask.save()
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('tracks:tasks', kwargs={'supertask_pk': target_pk}))
    else:
        query = Q(supertask=target_pk) & Q(user=user) & ~Q(pk=task_pk)
        tasks = Task.objects.filter(query).order_by('-pk')
        current_task = get_object_or_404(Task, task_query)
        supertask = get_object_or_404(Task, target_query)
    context = {
        'tasks': tasks,
        'current_task': current_task,
        'target_pk': target_pk,
        'breadcrumb': supertask.breadcrumb(),
    }
    return render(request, 'crackers/move.html', context)


@require_http_methods(['DELETE'])
@login_required
def delete_selected(request):
    data = QueryDict(request.body).dict()
    data.pop('csrfmiddlewaretoken', None)
    tasks = Task.objects.filter(user=request.user, pk__in=data)
    if tasks.exists():
        supertask = tasks.first().supertask
        tasks.delete()
        if supertask:
            return HTTPResponseHXRedirect(redirect_to=reverse_lazy('tracks:tasks', kwargs={'supertask_pk': supertask.pk}))
    return HTTPResponseHXRedirect(redirect_to=request.META.get('HTTP_REFERER'))

crackers/templates/crackers/landingpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="text-center">
  <h1>Welcome to SuperTodo</h1>
  
  <h2>Set up your objective.</h2>
  <img src="{% static 'Main.png' %}" alt="example" style="width: 70%">
  <h2>Divide and conquer.</h2>
  
  <p class="btn btn-info" hx-get="{% url 'accounts:login' %}" hx-target="body" hx-replace-url="true">Begin now</p>
</div>
{% endblock content %}

crackers/templates/crackers/move.html
{% extends 'base.html' %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'tracks:move_objective' current_task.pk %}">Top</a></li>
    {% for crumb in breadcrumb %}
    {% if forloop.last %}
    <li class="breadcrumb-item active" aria-current="page">{{ crumb.title }}</li>
    {% else %}
    <li class="breadcrumb-item"><a href="{% url 'tracks:move_task' current_task.pk crumb.pk %}">{{ crumb.title }}</a></li>
    {% endif %}
    {% endfor %}
  </ol>
</nav>

<h1>Move Task {{ current_task.title }}</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Task</th>
      <th scope="col">Achievement</th>
      <th scope="col">Weight</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <td><a href="{% url 'tracks:move_task' current_task.pk task.pk %}">{{ task.title }}</a></td>
      <td>
        <div class="progress" role="progressbar" aria-label="task-achievement" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
          {% widthratio task.pseudo_achievement 1 100 as width %}
          <div id="task-progress-{{ task.pk }}" class="progress-bar bg-info text-body" style="width: {{ width }}%">
            {% if task.marked_complete %}Marked Complete{% else %}{{ width }}% Achieved{% endif %}
          </div>
        </div>
      </td>
      <td>{{ task.proportion }}</td>
    </tr>
    {% if forloop.last %}
    {% if target_pk %}
    <tr class="pointer">
      <td colspan="3" hx-put="{% url 'tracks:move_task' current_task.pk target_pk %}">Move Task Here.</td>
    </tr>
    {% else %}
    <tr class="pointer">
      <td colspan="3" hx-put="{% url 'tracks:move_objective' current_task.pk %}">Set as an Objective</td>
    </tr>
    {% endif %}
    {% endif %}
    {% empty %}
    {% if target_pk %}
    <tr class="pointer">
      <td colspan="3" hx-put="{% url 'tracks:move_task' current_task.pk target_pk %}">Subtask does not exist. Move Task Here.</td>
    </tr>
    {% else %}
    <tr class="pointer">
      <td colspan="3" hx-put="{% url 'tracks:move_objective' current_task.pk %}">Subtask does not exist. Move Task Here.</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
  <caption>
    <div class="d-flex justify-content-end">
      <div>
        <a href="{% url 'tracks:tasks' current_task.pk %}" class="btn btn-link btn-sm mx-3">Cancel</a>
      </div>
    </div>
  </caption>
</table>
{% endblock content %}

crackers/templates/crackers/tasks.html
{% extends base_template %}
{% load static %}
{% load custom_filters %}
{% block task_template %}
<form hx-delete="{% url 'tracks:delete_selected' %}" hx-trigger="click from:#delete-selected" hx-target="body">
  {% csrf_token %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">
          <input 
            class="form-check-input"
            type="checkbox"
            name="select-all"
            id="select-all"
            onclick="selectAll()"
          >
        </th>
        <th scope="col">Task</th>
        <th scope="col">Achievement</th>
        <th scope="col">Completed</th>
        <th scope="col">Details</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
      <tr id="table-row-{{ task.pk }}">
        <td>
          <div class="form-check d-flex justify-content-center">
            <input id="delete-checkbox-for-{{ task.pk }}" class="form-check-input" type="checkbox" name="{{ task.pk }}" onclick="updateSelectAll()">
          </div>
        </td>
        <td>
          <a class="btn btn-sm justify-content-center" href="{% url 'tracks:tasks' task.pk %}">
            {{ task.title }}
          </a>
        </td>
        <td>
          <div class="progress" role="progressbar" aria-label="task-achievement" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
            {% widthratio task.pseudo_achievement 1 100 as width %}
            <div id="task-progress-{{ task.pk }}" class="progress-bar bg-info text-body" style="width: {{ width }}%">
              {% if task.marked_complete %}Marked Complete{% else %}{{ width }}% Achieved{% endif %}
            </div>
          </div>
        </td>
        <td>
          <div class="form-check d-flex justify-content-center">
            <input
            hx-put="{% url 'tracks:complete' task.pk %}"
            hx-swap="none"
            hx-trigger="click"
            class="form-check-input"
            type="checkbox"
            id="flexCheckChecked" {% if task.completed %}checked{% endif %} {% if task|all_completed %}disabled{% endif %}>
          </div>
        </td>
        <td>
          <span id="detail-btn-for-{{ task.pk }}"
          class="btn btn-outline-dark btn-sm"
          hx-target="#table-row-{{ task.pk }}"
          hx-get="{% url 'tracks:detail' task.pk %}"
          hx-swap="afterend"
          >Detail</span>
        </td>
      </tr>
      {% if forloop.last %}
      <tr>
        <td colspan="5" style="transform: rotate(0)">
          <a
          class="stretched-link text-decoration-none text-primary"
          {% if supertask %}
          href="{% url 'tracks:create_subtask' supertask.pk %}">Create subtask
          {% else %}
          href="{% url 'tracks:create' %}">Create objective
          {% endif %}
          </a>
        </td>
      </tr>
      {% endif %}
      {% empty %}
      <tr class="pointer">
        <td colspan="5" style="transform: rotate(0)">
          <a class="stretched-link text-decoration-none text-body-emphasis" href="{% if supertask %}{% url 'tracks:create_subtask' supertask.pk %}{% else %}{% url 'tracks:create' %}{% endif %}">
            There's no related subtask. Create one.
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <caption>
      <div class="d-flex justify-content-start">
        <button class="btn btn-sm btn-link" id="delete-selected">Delete Selected</button>
        {% if supertask %}
        {% if supertask == objective %}
        <a class="btn btn-link btn-sm" href="{% url 'tracks:update' supertask.pk %}">Update Objective</a>
        <a class="btn btn-link btn-sm" href="{% url 'tracks:move_objective' supertask.pk %}">Move Objective</a>
        <a class="btn btn-link btn-sm"
        hx-delete="{% url 'tracks:delete' supertask.pk %}"
        hx-confirm="This action deletes all related subtasks.">Delete Objective</a>
        {% else %}
        <a class="btn btn-link btn-sm" href="{% url 'tracks:update' supertask.pk %}">Update Task</a>
        <a class="btn btn-link btn-sm" href="{% url 'tracks:move_objective' supertask.pk %}">Move Task</a>
        <a class="btn btn-link btn-sm"
        hx-delete="{% url 'tracks:delete' supertask.pk %}"
        hx-confirm="This action deletes all related subtasks.">Delete Task</a>
        {% endif %}
        {% endif %}
      </div>
    </caption>
  </table>
</form>
<script src="{% static 'crackers/utils.js' %}"></script>
{% endblock task_template %}

crackers/templates/crackers/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>{{ title }}</h1>
{% with form.instance as instance %}
<form hx-put="{% url 'tracks:update' instance.pk %}" hx-include="[name='_path']">
  <input type="hidden" name="_path" value={{ path }}>
  {% with form.title as title %}
  <div class="form-group my-3">
    <label for="{{ title.id_for_label }}">{{ title.label }}</label>
    <input autofocus required type="{{ title.field.widget.input_type }}" class="form-control" value="{{ instance.title }}" placeholder="{{ title.label }}" name="{{ title.name }}" />
  </div>
  {% endwith %}
  
  {% with form.description as description %}
  <div class="form-group my-3">
    <label for="{{ description.id_for_label }}">{{ description.label }}</label>
    <textarea id="{{ description.id_for_label }}" class="form-control" placeholder="{{ description.label }}" name="{{ description.name }}">{{ instance.description }}</textarea>
  </div>
  {% endwith %}

  {% with form.proportion as proportion %}
  <label for="{{ proportion.id_for_label }}">{{ proportion.label }}</label>
  {% if form.instance.supertask and form.instance.supertask.accumulative %}
  <p class="my-1 mb-0 text-danger">Accumulated. If you don't want it accumulated, uncheck 'Accumuated subtask weight' in your supertask.</p>
  {% endif %}
  <div class="input-group mt-0 mb-3">
    <input id="{{ proportion.id_for_label }}" required type="{{ proportion.field.widget.input_type }}" class="form-control" placeholder="{{ proportion.label }}" name="{{ proportion.name }}" value="{{ instance.proportion }}" />
    <button id="sexagesimal-to-decimal-btn-proportion" class="btn btn-outline-primary" type="button" data-input-id="{{ proportion.id_for_label }}">Convert sexagesimal number to decimal.</button>
  </div>
  {% endwith %}


  {% with form.accumulative as accumulative %}
  <div class="form-check">
    <label class="form-check-label" for="{{ accumulative.id_for_label }}">{{ accumulative.label }} </label>
    <input id="{{ accumulative.id_for_label }}" class="form-check-input" type="{{ accumulative.field.widget.input_type }}" name="{{ accumulative.name }}" {% if instance.accumulative %}checked{% endif %}>
    <p class="my-1">If you check, it will calculated appropriate weight from your accumulated value.</p>
    <p class="my-1 mb-3">For example, if your task is reading a book, say chapter 1 ends at pg 35 and chapter 2 at 60. Then you can just put 35 and 60 and it will calculate their weight 35 and 25 respectively.</p>
  </div>
  {% endwith %}
  
  {% with form.start as start %}
  <div id="div-{{ start.id_for_label }}" class="mb-3 mt-0{% if not instance.accumulative %} d-none{% endif %}">
    <label for="{{ start.id_for_label }}">{{ start.label }} 👈 If your subtasks' weight is accumulated, you can set starting point.</label>
    <p class="my-1 mb-3">For example, say chapter 2 starts at pg 36, while section 1 starts at pg 42 and section 2 at 50. Then setting starting point at 36 will let their weight be calculated as 6 and 8 respectively.</p>
    <div class="input-group">
      <input id="{{ start.id_for_label }}" required type="{{ start.field.widget.input_type }}" class="form-control" placeholder="{{ start.label }}" name="{{ start.name }}" value="{% if instance.accumulative %}{{ instance.start }}{% else %}0{% endif %}" />
      <button id="sexagesimal-to-decimal-btn-start" class="btn btn-outline-primary" type="button" data-input-id="{{ start.id_for_label }}">Convert sexagesimal number to decimal.</button>
    </div>
  </div>
  {% endwith %}

  <button class="btn btn-primary" type="submit">UPDATE</button>
</form>
{% endwith %}
<script>
  const accumulative = document.getElementById('{{ form.accumulative.id_for_label }}')
  const start = document.getElementById('div-{{ form.start.id_for_label }}')
  accumulative.addEventListener('click', (e) => {
    start.classList.toggle('d-none')
  })
</script>
<script src="{% static 'crackers/sexagesimalConverter.js' %}"></script>
{% endblock content %}