accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crackers.urls')),
    path('accounts/', include('accounts.urls')),
]

crackers/urls.py
from django.urls import path

from . import views

app_name = 'tracks'
urlpatterns = [
    path('', views.index, name='index'),   # all objectives. 이후 로그인 되어있지 않으면 landingpage, 되어있다면 all objectives.
    path('create/', views.create, name='create'),   # create task
    path('<int:supertask_pk>/', views.tasks, name='tasks'),   # subtask list
    path('<int:supertask_pk>/create/', views.create, name='create_subtask'),   # create subtask
    path('<int:supertask_pk>/detail/', views.detail, name='detail'),
    path('<int:task_pk>/update/', views.update, name='update'),
    path('<int:task_pk>/delete/', views.delete, name='delete'),
    path('<int:task_pk>/complete/', views.complete, name='complete'),
    path('<int:supertask_pk>/detail_paginator/', views.detail_paginator, name='detail_paginator'),
    path('<int:task_pk>/move/', views.move_objective, name='move_objective'),
    path('<int:task_pk>/move/<int:target_pk>/', views.move_task, name='move_task'),
    path('delete-selected/', views.delete_selected, name='delete_selected')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>🍪 Track Crackers</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<style>
  .pointer {
    cursor: pointer;
  }
  td, th {
    text-align: center;
    vertical-align: middle;
  }
</style>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'tracks:index' %}">SuperTodo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'tracks:index' %}">Home</a>
          </li>
        </ul>
      </div>
      {% if user.is_authenticated %}
      <div hx-get="{% url 'accounts:logout' %}" hx-target="body" class="btn btn-primary mx-1">Logout</div>
      {% else %}
      <div hx-get="{% url 'accounts:login' %}" hx-target="body" hx-replace-url="true" class="btn btn-primary mx-1">Login</div>
      <div hx-get="{% url 'accounts:signup' %}" hx-target="body" hx-replace-url="true" class="btn btn-primary mx-1">Signup</div>
      {% endif %}
    </div>
  </nav>
  
  <main class="container">
    {% block content %}
    {% endblock content %}
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  {# htmx@1.9.2 #}
  <script src="{% static 'htmx.min.js' %}"></script>
  <script src="{% static 'eventHandlers.js' %}"></script>
</body>
</html>